# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Documentation:
# https://www.mkdocs.org/getting-started/
# https://www.mkdocs.org/user-guide/
# https://squidfunk.github.io/mkdocs-material/
# https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/index.html
# https://guts.github.io/mkdocs-rss-plugin/
site_name: MVHS Workshop Python für Automatisierungs- und Scripting-Aufgaben
site_url: https://maroph.github.io/mvhs_python_automatisierung_scripting/
site_description: Meine Daten aus dem MVHS Workshop Python für Automatisierungs- und Scripting-Aufgaben
site_author: Manfred Rosenboom (maroph)

repo_url: https://github.com/maroph/mvhs_python_automatisierung_scripting/
repo_name: maroph/mvhs_python_automatisierung_scripting
edit_uri: edit/main/docs
# view readonly version                  edit_uri: blob/main/docs
# link to GitHub repository site only    edit_uri: ""

theme:
    name: material
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    font: false
    language: de
    logo: assets/python-logo-only2.png
    direction: ltr
    favicon: assets/favicon.ico
    features:
        - header.autohide
        - content.action.edit
        - content.action.view
        - content.code.copy
        - content.tooltips
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.prune
        - navigation.sections
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - search.suggest
        - search.highlight
        - toc.follow
#        - toc.integrate
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye
        previous: fontawesome/solid/angle-left
        next: fontawesome/solid/angle-right

nav:
    - Home: index.md
    - Workshop:
        - workshop.md
        - Links: workshop/links.md
        - Tag 1: workshop/tag1.md
        - Tag 2: workshop/tag2.md
        - Tag 3: workshop/tag3.md
    - Python:
        - python.md
        - Links: python/links.md
        - Dictionaries: python/dictionaries.md
        - Funktionsargumente: python/func_args.md
        - Hashable: python/hashable.md
        - Listen: python/listen.md
        - Sets: python/sets.md
        - SQLite: python/sqlite.md
        - Tuples: python/tuples.md
    - Info:
        - info.md
        - Über: info/about.md
        - Lizenz: info/license.md
        - DSGVO: info/gdpr.md
        - Quellen: info/sources.md
    - Blog: blog/index.md

docs_dir: docs
site_dir: site

use_directory_urls: false
strict: true

copyright: Copyright (c) 2025 CC-BY 4.0 <a href="https://maroph.github.io/">Manfred Rosenboom (maroph)</a>

markdown_extensions:
    - attr_list
# available icons, emojis: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables

plugins:
# https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/index.html
    - git-revision-date-localized:
          enable_creation_date: false
          fallback_to_build_date: true
          timezone: Europe/Amsterdam
          type: iso_datetime
    - info:
          enabled: false
    - meta:
          enabled: true
    - offline:
          enabled: false
    - privacy:
          enabled: true
          cache: true
    - search:
          enabled: true
          lang: de
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#writing-your-first-post
# https://squidfunk.github.io/mkdocs-material/plugins/blog/
    - blog:
        enabled: true
        authors: true
        blog_dir: blog
        blog_toc: true
        draft: false
        draft_on_serve: false
        draft_if_future_date: false
        pagination: true
        pagination_per_page: 10
        pagination_url_format: "page/{page}"
# https://babel.pocoo.org/en/latest/dates.html#pattern-syntax
        post_date_format: "dd. MMMM YYYY, H:mm"
        pagination_if_single_page: false
        post_excerpt: optional
        post_excerpt_separator: "<!-- more -->"
        post_readtime: false
        archive: true
        archive_name: Archiv
        archive_date_format: yyyy
        archive_url_format: "archiv/{date}"
        archive_toc: true
        categories: false

# https://guts.github.io/mkdocs-rss-plugin/configuration/
    - rss:
        enabled: true
        match_path: "blog/posts/.*"
        abstract_chars_count: 160
        abstract_delimiter: "<!-- more -->"
        date_from_meta:
            as_creation: "date"
            as_update: "updated"
            datetime_format: "%Y-%m-%d %H:%M"
            default_time: "12:00"
            default_timezone: Europe/Berlin
        feed_description: Mein Blog zum MVHS Workshop Python für Automatisierungs- und Scripting-Aufgaben
        feed_title: Blog
        feed_ttl: 1440
#    logo: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
        image: https://maroph.github.io/blog/assets/128px-Feed-icon.svg.png
        json_feed_enabled: false
        length: 10
        use_git: false
        use_material_blog: true

extra:
    generator: true
#icons: https://fontawesome.com/search?o=r&f=brands
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/maroph
          name: github.com/maroph
        - icon: fontawesome/brands/mastodon
          link: https://mastodon.social/@maroph
          name: mastodon.social/@maroph
