authors:
    maroph:
        name: Manfred Rosenboom
        description: Web Site Creator
        avatar: https://maroph.github.io/mvhs_python_automatisierung_scripting/assets/github_maroph_1909126.jpg
        url: https://github.com/maroph
